## Top-k Accuracy
> XCurve.Metrics.TopkAcc(y_pred, y_true, k_list=(1, ))

### Brief Introductions
Compute the top-k accuracy for each k in the specified k-list. For each k value, this metric can be denoted as:
$$
    \text{Acc}_k(f) = \frac{1}{n} \sum_{i=1}^{n} \mathbb{I} \left( f(x_i)_{y_i} > f(x_i)_{[k]} \right),
$$
where $f(x_i)_{y_i}$ is the score of the ground-truth label, $f(x_i)_{[k]}$ is the $k$-largest value in $f(x) \in \mathbb{R}^C$, $C$ denotes the number of classes, and $\mathbb{I}(\cdot)$ is the indicator function. 

For more details, please refer to the literature:
> Optimizing Partial Area Under the Top-k Curve: Theory and Practice. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. T-PAMI, 2023. 

### Code Instructions

#### Parameters
- y_pred: Prediction score (torch array with shape (n_samples, n_classes)).
- y_true: True labels (torch array with shape (n_samples,)). 
- k_list: The specified k-list

#### Return
- Top-k Accuracy (list): return the top-k accuracy for each k in the specified k-list, where the values are multiplied by 100.

#### Example

In [21]:
from Metrics import TopkAcc
import numpy as np 
import torch

# binary cases
n_samples = 10
C = 5
k_list = (1, 3)
y_true = np.random.randint(low=0, high=C, size=(n_samples, ))
y_pred = np.random.rand(n_samples, C)
print(y_true, y_pred)
y_true = torch.from_numpy(y_true)
y_pred = torch.from_numpy(y_pred)

topk_acc=TopkAcc(y_pred, y_true, k_list)
print(topk_acc)

[3 2 4 1 1 1 4 4 2 4] [[0.19164027 0.34880401 0.01405983 0.63749076 0.4723965 ]
 [0.37742356 0.91971887 0.75663368 0.88626164 0.28900607]
 [0.70599817 0.14515437 0.92703292 0.25546784 0.53140083]
 [0.43893413 0.65771666 0.84103903 0.0599529  0.91868449]
 [0.98505314 0.14926645 0.39919683 0.2809031  0.24024436]
 [0.17448092 0.36092299 0.47050776 0.08721417 0.27165934]
 [0.35809422 0.58765591 0.73592721 0.14659405 0.99683407]
 [0.14213289 0.07431412 0.87194129 0.19784914 0.49950462]
 [0.77964809 0.66647467 0.37650761 0.78635834 0.68518816]
 [0.87429223 0.65933281 0.22680662 0.01083235 0.7975534 ]]
[tensor(20.), tensor(80.)]
