## Top-k Accuracy
> XCurve.Metrics.TopkAcc(y_pred, y_true, k_list=(1, ))

### Brief Introductions
Compute the top-k accuracy for each k in the specified k-list. For each k value, this metric can be denoted as:
$$
    \text{Acc}_k(f) = \frac{1}{n} \sum_{i=1}^{n} \mathbb{I} \left( f(x_i)_{y_i} > f(x_i)_{[k]} \right),
$$
where $f(x_i)_{y_i}$ is the score of the ground-truth label, $f(x_i)_{[k]}$ is the $k$-largest value in $f(x) \in \mathbb{R}^C$, $C$ denotes the number of classes, and $\mathbb{I}(\cdot)$ is the indicator function. 

For more details, please refer to the literature:
> Optimizing Partial Area Under the Top-k Curve: Theory and Practice. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. T-PAMI, 2023. 

### Code Instructions

#### Parameters
- y_pred: Prediction score (torch array with shape (n_samples, n_classes)).
- y_true: True labels (torch array with shape (n_samples,)). 
- k_list: The specified k-list

#### Return
- Top-k Accuracy (list): return the top-k accuracy for each k in the specified k-list, where the values are multiplied by 100.

#### Example

In [12]:
# from Metrics import TopkAcc
from XCurve.Metrics import TopkAcc
import numpy as np 
import torch

n_samples, C = 10, 5
k_list = (1, 3)
y_true = np.random.randint(low=0, high=C, size=(n_samples, ))
y_pred = np.random.rand(n_samples, C)
print(y_true, y_pred)
y_true = torch.tensor(y_true)
y_pred = torch.tensor(y_pred)

topk_acc=TopkAcc(y_pred, y_true, k_list)
print(topk_acc)

[1 4 4 4 1 3 3 3 2 1] [[0.64838829 0.55347873 0.54402452 0.44256019 0.93269784]
 [0.90289872 0.20138704 0.535019   0.09570918 0.82571798]
 [0.56390727 0.54268805 0.51674891 0.38070372 0.88541311]
 [0.7735994  0.91112566 0.16059716 0.55685722 0.3408125 ]
 [0.02986079 0.25893837 0.77636374 0.19880775 0.45766495]
 [0.34103661 0.78989861 0.92651628 0.93653775 0.98839753]
 [0.29854327 0.52052683 0.87691339 0.67445962 0.67494816]
 [0.0353367  0.73544842 0.31514033 0.87075895 0.86990737]
 [0.71549516 0.65359928 0.15977091 0.09389867 0.25932929]
 [0.25369997 0.84567305 0.51449316 0.54070907 0.51912976]]
[tensor(30.), tensor(80.)]


## AUTKC
> XCurve.Metrics.AUTKC(y_pred, y_true, k_list=(1, ))

### Brief Introductions
Compute AUTKC for each K in the specified K-list. For each K value, this metric can be denoted as:
$$
    \text{AUTKC}(f) = \frac{1}{n K} \sum_{i=1}^{n} \sum_{k=1}^{K} \mathbb{I} \left( f(x_i)_{y_i} > f(x_i)_{[k]} \right),
$$
where $f(x_i)_{y_i}$ is the score of the ground-truth label, $f(x_i)_{[k]}$ is the $k$-largest value in $f(x) \in \mathbb{R}^C$, $C$ denotes the number of classes, and $\mathbb{I}(\cdot)$ is the indicator function. 

For more details, please refer to the literature:
> Optimizing Partial Area Under the Top-k Curve: Theory and Practice. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. T-PAMI, 2023. 

### Code Instructions

#### Parameters
- y_pred: Prediction score (torch array with shape (n_samples, n_classes)).
- y_true: True labels (torch array with shape (n_samples,)). 
- k_list: The specified k-list

#### Return
- AUTKC (list): return the AUTKC value for each K in the specified K-list, where the values are multiplied by 100.

#### Example

In [13]:
# from Metrics import AUTKC
from XCurve.Metrics import TopkAcc, AUTKC
import numpy as np 
import torch

n_samples, C = 10, 5
k_list = (1, 3)
y_true = np.random.randint(low=0, high=C, size=(n_samples, ))
y_pred = np.random.rand(n_samples, C)
print(y_true, y_pred)
y_true = torch.LongTensor(y_true)
y_pred = torch.tensor(y_pred)

autkc=AUTKC(y_pred, y_true, k_list)
print(autkc)

[1 2 0 0 0 1 2 0 2 0] [[0.32585825 0.71367106 0.36318442 0.01938121 0.48031555]
 [0.13788876 0.25927396 0.68111324 0.0337897  0.24350969]
 [0.65350215 0.80755938 0.33121928 0.7923216  0.2436303 ]
 [0.9621713  0.58982437 0.61118424 0.85345634 0.30304957]
 [0.60989384 0.03467619 0.79976203 0.23143927 0.3598388 ]
 [0.1030448  0.92547417 0.60763191 0.41588544 0.89665524]
 [0.82591484 0.83203993 0.65667892 0.27456011 0.30116539]
 [0.54332524 0.24978069 0.62992761 0.59985384 0.68540005]
 [0.25644439 0.35246559 0.13448705 0.57478406 0.43870188]
 [0.94486895 0.08842041 0.13716438 0.32860897 0.31104301]]
[tensor(50.), tensor(63.3333)]


## Macro Open-Set F-score
> XCurve.Metrics.MacroF(close_pred, close_labels, open_pred, open_labels, t_list)

### Brief Introductions
Compute Macro Open-Set F-score for each threshold in the given decision-making conditions. For each threshold, this metric can be denoted as:
$$
    \text{F-score}(f) = 2 \times \frac{\text{P}_\text{k}(f) \times \text{R}_\text{k}(f)}{\text{P}_\text{k}(f) + \text{R}_\text{k}(f)},
$$
where the precision and recall of known classes is defined as:
$$
    \text{P}_\text{k}(f) = \frac{1}{C} \sum_{i=1}^{C} \frac{\text{TP}_i}{\text{TP}_i + \text{FP}_i}, \text{R}_\text{k}(f) = \frac{1}{C} \sum_{i=1}^{C} \frac{\text{TP}_i}{\text{TP}_i + \text{FN}_i},
$$
and $\text{TP}_i, \text{FP}_i, \text{FN}_i$ are the True Positive (TP), False Positive (FP), False Negative (FN) performance of the close-set class $i$ under the given open-set decision threshold $t$, respectively; $C$ denotes the number of known classes (close-set). 

For more details, please refer to the literature:
> OpenAUC: Towards AUC-Oriented Open-Set Recognition. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. NeurIPS, 2022. 

> Nearest neighbors distance ratio open-set classifier. Pedro Ribeiro Mendes Júnior, Roberto Medeiros de Souza, Rafael de Oliveira Werneck, Bernardo V. Stein, Daniel V. Pazinato, Waldir R. de Almeida, Otávio A. B. Penatti, Ricardo da Silva Torres, Anderson Rocha. Mach. Lean., 2017.

### Code Instructions

#### Parameters
- close_pred: Predicted close-set scores (numpy array with shape (n_samples, n_classes)).
- close_labels: True close-set label (numpy array with shape (n_samples,)). 
- open_pred: Predicted open-set score (numpy array with shape (n_samples,)). 
- open_labels: True open-set label, which is binary (numpy array with shape (n_samples,)). 
- t_list: the list of open-set decision threshold

#### Return
- Macro Open-Set F-score (list): return the Macro Open-Set F-score under the given threshold list.

#### Example

In [14]:
from XCurve.Metrics import MacroF
import numpy as np 

n_samples, C = 10, 5
t_list = (0,2, 0.4, 0.6, 0.8)
close_pred = np.random.rand(n_samples, C)
close_labels = np.random.randint(low=0, high=C, size=(n_samples, ))
open_pred = np.random.rand(n_samples, )
open_labels = np.random.randint(low=0, high=2, size=(n_samples, ))
print(close_pred, close_labels, open_pred, open_labels)

MacroF_score = MacroF(close_pred, close_labels, open_pred, open_labels, t_list)
print(max(MacroF_score), MacroF_score)

[[0.22505163 0.56565412 0.4587647  0.30046217 0.25092002]
 [0.77524922 0.18918122 0.51540363 0.22983436 0.38370275]
 [0.86520307 0.60817761 0.4678875  0.93207612 0.21062528]
 [0.81050332 0.20231395 0.26201179 0.09741689 0.91836598]
 [0.80361421 0.86571197 0.41565162 0.98073268 0.51166106]
 [0.10264231 0.49819469 0.52019938 0.58886308 0.61867914]
 [0.23672743 0.28810752 0.34941579 0.64526916 0.97516705]
 [0.8195246  0.31829393 0.31659231 0.21084115 0.59936089]
 [0.63162671 0.82508019 0.05080957 0.88448093 0.32695938]
 [0.16358325 0.31049377 0.26492354 0.94893459 0.21349402]] [1 0 0 4 1 3 0 4 3 0] [0.58096977 0.72253053 0.97245012 0.10536401 0.92602635 0.23475404
 0.78746598 0.16379799 0.0078515  0.70920022] [1 1 1 0 1 0 1 1 0 1]
0.5714285714285715 [0, 0.30769230769230765, 0.5714285714285715, 0.5, 0.36363636363636365]


## Micro Open-Set F-score
> XCurve.Metrics.MicroF(close_pred, close_labels, open_pred, open_labels, t_list)

### Brief Introductions
Compute Micro Open-Set F-score for each threshold in the given decision-making conditions. For each threshold, this metric can be denoted as:
$$
    \text{F-score}(f) = 2 \times \frac{\text{P}_\text{k}(f) \times \text{R}_\text{k}(f)}{\text{P}_\text{k}(f) + \text{R}_\text{k}(f)},
$$
where the precision and recall of known classes is defined as:
$$
    \text{P}_\text{k}(f) = \frac{\sum_{i=1}^{C} \text{TP}_i}{\sum_{i=1}^{C} (\text{TP}_i + \text{FP}_i)}, \text{R}_\text{k}(f) = \frac{\sum_{i=1}^{C} \text{TP}_i}{\sum_{i=1}^{C} (\text{TP}_i + \text{FN}_i)},
$$
and $\text{TP}_i, \text{FP}_i, \text{FN}_i$ are the True Positive (TP), False Positive (FP), False Negative (FN) performance of the close-set class $i$ under the given open-set decision threshold $t$, respectively; $C$ denotes the number of known classes (close-set). 

For more details, please refer to the literature:
> OpenAUC: Towards AUC-Oriented Open-Set Recognition. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. NeurIPS, 2022. 

> Nearest neighbors distance ratio open-set classifier. Pedro Ribeiro Mendes Júnior, Roberto Medeiros de Souza, Rafael de Oliveira Werneck, Bernardo V. Stein, Daniel V. Pazinato, Waldir R. de Almeida, Otávio A. B. Penatti, Ricardo da Silva Torres, Anderson Rocha. Mach. Lean., 2017.

### Code Instructions

#### Parameters
- close_pred: Predicted close-set scores (numpy array with shape (n_samples, n_classes)).
- close_labels: True close-set label (numpy array with shape (n_samples,)). 
- open_pred: Predicted open-set score (numpy array with shape (n_samples,)). 
- open_labels: True open-set label, which is binary (numpy array with shape (n_samples,)). 
- t_list: the list of open-set decision threshold

#### Return
- Micro Open-Set F-score (list): return the Micro Open-Set F-score under the given threshold list.

#### Example

In [15]:
from XCurve.Metrics import MicroF
import numpy as np 

n_samples, C = 10, 5
t_list = (0,2, 0.4, 0.6, 0.8)
close_pred = np.random.rand(n_samples, C)
close_labels = np.random.randint(low=0, high=C, size=(n_samples, ))
open_pred = np.random.rand(n_samples, )
open_labels = np.random.randint(low=0, high=2, size=(n_samples, ))
print(close_pred, close_labels, open_pred, open_labels)

MicroF_score = MicroF(close_pred, close_labels, open_pred, open_labels, t_list)
print(max(MicroF_score), MicroF_score)

[[0.94476045 0.31232958 0.7594962  0.5459496  0.11673619]
 [0.40129684 0.46983343 0.59049727 0.02780379 0.39378312]
 [0.09031484 0.39312287 0.7456237  0.68701889 0.6515781 ]
 [0.96727651 0.32777401 0.31835944 0.32121615 0.60035559]
 [0.12668534 0.74379642 0.67996953 0.0638046  0.93851802]
 [0.85612227 0.81200387 0.71530705 0.56665163 0.3869682 ]
 [0.35571454 0.52809497 0.80250131 0.65778885 0.01543388]
 [0.45475614 0.64144596 0.37641412 0.54375577 0.80926811]
 [0.234557   0.84534896 0.25663904 0.57333292 0.1715498 ]
 [0.97534425 0.86363475 0.79658496 0.98944572 0.01503485]] [1 0 2 2 3 3 2 4 2 1] [0.43159292 0.54486159 0.71308451 0.32513637 0.33009744 0.01605909
 0.32385449 0.34015317 0.31708952 0.51067112] [0 1 0 0 0 1 1 0 1 1]
0.21428571428571427 [0, 0.21428571428571427, 0.13333333333333333, 0.13333333333333333, 0.21428571428571427]


## Close-set Accuracy
> XCurve.Metrics.ClosedSetAcc(preds, labels)

### Brief Introductions
Compute the close-set accuracy, which is exactly the same as that for the traditional multiclass classification. For more details, please refer to the literature:
> OpenAUC: Towards AUC-Oriented Open-Set Recognition. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. NeurIPS, 2022. 

### Code Instructions

#### Parameters
- preds: Predicted close-set scores (numpy array with shape (n_samples, n_classes)).
- labels: True close-set label (numpy array with shape (n_samples,)). 

#### Return
- Close-set accuracy (int): return the close-set accuracy of the given predictions.

#### Example

In [16]:
from XCurve.Metrics import ClosedSetAcc
import numpy as np 

n_samples, C = 10, 5
close_pred = np.random.rand(n_samples, C)
close_labels = np.random.randint(low=0, high=C, size=(n_samples, ))
print(close_pred, close_labels)

acc = ClosedSetAcc(close_pred, close_labels)
print(acc)

[[0.49754002 0.68136726 0.00655441 0.7307169  0.24021935]
 [0.68390136 0.02843787 0.73061857 0.82048215 0.29817192]
 [0.85291294 0.22381565 0.44356664 0.20900793 0.71125885]
 [0.99540302 0.22050627 0.60666405 0.69529683 0.23555486]
 [0.57980707 0.64937927 0.74586459 0.54480237 0.40103413]
 [0.39926519 0.89198329 0.81554857 0.34728837 0.18800771]
 [0.57526907 0.81787129 0.00900459 0.8563558  0.06290815]
 [0.32171042 0.08209535 0.96669313 0.05638027 0.58086259]
 [0.97084678 0.04685043 0.93050665 0.14153485 0.88362274]
 [0.01322846 0.19979784 0.43723429 0.97349314 0.17223946]] [0 1 3 2 0 0 0 1 0 3]
0.2


## Open-set Accuracy at Given Ratio of Open-Set TPR performance 
> XCurve.Metrics.Acc_At_TPR(open_set_preds, open_set_labels, r=0.95)

### Brief Introductions
Compute the open-set accuracy at the given ratio of open-set TPR performance. For more details, please refer to the literature:
> Open-Set Recognition: A Good Closed-Set Classifier is All You Need. Sagar Vaze, Kai Han, Andrea Vedaldi, Andrew Zisserman. ICLR, 2022.

### Code Instructions

#### Parameters
- open_set_preds: Predicted open-set score (numpy array with shape (n_samples, )).
- open_set_labels: True open-set label (numpy array with shape (n_samples,)). 
- r: The specific ratio of the TPR performance (float, 0.95 default).

#### Return
- Open-set Accuracy at Given Ratio of Open-Set TPR performance (int).

#### Example

In [17]:
from XCurve.Metrics import Acc_At_TPR
import numpy as np 

n_samples, C = 10, 5
open_pred = np.random.rand(n_samples)
open_labels = np.random.randint(low=0, high=2, size=(n_samples, ))
print(open_pred, open_labels)

acc_at_95_tpr = Acc_At_TPR(open_pred, open_labels, 0.95)
print(acc_at_95_tpr)

[0.52927694 0.35955991 0.05612158 0.43284317 0.21076107 0.04785475
 0.20930379 0.79965758 0.31728419 0.99811264] [0 1 1 0 1 0 1 0 1 1]
0.7


## Open-set AUROC
> XCurve.Metrics.AUROC(open_set_preds, open_set_labels)

### Brief Introductions
Compute the open-set AUROC, which is exactly the same as that for binary classification and novelty dectection. For more details, please refer to the literature:
> OpenAUC: Towards AUC-Oriented Open-Set Recognition. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. NeurIPS, 2022. 

### Code Instructions

#### Parameters
- open_set_preds: Predicted open-set score (numpy array with shape (n_samples, )).
- open_set_labels: True open-set label (numpy array with shape (n_samples,)). 

#### Return
- Open-set AUROC (int).

#### Example

In [18]:
from XCurve.Metrics import AUROC
import numpy as np 

n_samples, C = 10, 5
open_pred = np.random.rand(n_samples)
open_labels = np.random.randint(low=0, high=2, size=(n_samples, ))
print(open_pred, open_labels)


acc_at_95_tpr = AUROC(y_true = open_labels, y_pred = open_pred)
print(acc_at_95_tpr)


[0.77690503 0.16216813 0.2373073  0.30772442 0.06389388 0.90795935
 0.15873279 0.77110265 0.19173886 0.70849355] [0 0 1 1 1 1 1 1 0 1]
0.523809523809524


## OpenAUC
> XCurve.Metrics.OpenAUC(open_set_pred_known, open_set_pred_unknown, close_set_pred_class, close_set_labels)

### Brief Introductions
Compute the OpenAUC score, which is denoted as:
$$
    \text{OpenAUC}(h, r) = \frac{1}{N_k N_u} \sum_{i = 1}^{N_k} \sum_{j = 1}^{N_u} \mathbb{I}(h(x_i) = y_i) \cdot \mathbb{I}(r(x_j) > r(x_i)),
$$
where $h: \mathcal{X} \to \mathcal{Y}_k$ represents the close-set classifier, $r: \mathcal{X} \to \mathbb{R}$ denotes the open-set ranker; $(x_i, y_i)$ and $x_j$ are sampled from close-set and open-set, respectively.

> OpenAUC: Towards AUC-Oriented Open-Set Recognition. Zitai Wang, Qianqian Xu, Zhiyong Yang, Yuan He, Xiaochun Cao and Qingming Huang. NeurIPS, 2022. 

### Code Instructions

#### Parameters
- open_set_pred_known: Predicted open-set score of close-set samples (numpy array with shape (n_close_samples, )).
- open_set_pred_unknown: Predicted open-set score of open-set samples (numpy array with shape (n_open_samples,)). 
- close_set_pred_class: Predicted close-set class of close-set samples (numpy array with shape (n_close_samples, )).
- close_set_labels: True close-set class of close-set samples (numpy array with shape (n_close_samples, )).

#### Return
- OpenAUC (int).

#### Example

In [19]:
from XCurve.Metrics import OpenAUC
import numpy as np 

n_close_samples, C, n_open_samples = 10, 5, 8
open_set_pred_known = np.random.rand(n_close_samples)
open_set_pred_unknown = np.random.rand(n_open_samples)
close_set_pred_class = np.random.randint(low=0, high=C, size=(n_close_samples, ))
close_set_labels = np.random.randint(low=0, high=C, size=(n_close_samples, ))
print(open_set_pred_known, open_set_pred_unknown, close_set_pred_class, close_set_labels)

openauc = OpenAUC(open_set_pred_known, open_set_pred_unknown, close_set_pred_class, close_set_labels)
print(openauc)

[0.10813683 0.46179204 0.46586681 0.38944239 0.06500318 0.85720791
 0.23660373 0.39949662 0.12335166 0.80062615] [0.01781371 0.48136111 0.58010638 0.54412853 0.44452411 0.05729807
 0.2351886  0.64246962] [3 2 3 0 0 1 1 2 2 2] [2 2 2 1 4 0 3 3 0 0]
0.04999999999999999
